engines:
  phpcodesniffer:
    enabled: true
    config:
      standard: "WordPress"
  eslint:
    enabled: true
  scss-lint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - php
      - javascript
ratings:
exclude_paths:
  - tests/*
  - assets/js/dist/*
  - assets/js/task-breaker.dev.js
  - assets/js/task-breaker.min.js
  - assets/js/task-breaker.min.js.map
  